#!/bin/bash
repo_dir="/work/sshirzad/repos/VascularModelingData"
exec_dir="/home/sshirzad/src/VascularModeling/Radiation\ Modeling\ Projects/build/Output"
results_dir="${repo_dir}/results"

source "${repo_dir}"/gcc_rostam.sh
ranks=$1
gen=$2
dim=$3

echo "running BloodFlowModeling on ${ranks} ranks for ${gen} generations and ${dim} dimensions"

echo "srun -p medusa -n ${ranks} --mpi=pmi2 ${exec_dir}/BloodFlowModeling ${results_dir}/geometry_${ranks}_${gen}_${dim}.h5"| tee ${results_dir}/BloodFlowModelinglog_${ranks}_${gen}_${dim}.txt

cd /home/sshirzad/src/VascularModeling/Radiation\ Modeling\ Projects/build/Output 
#srun -p medusa -n ${ranks} --mpi=pmi2 BloodFlowModeling -1 ${results_dir}/geometry_${ranks}_${gen}_${dim}.h5>>${results_dir}/DoseMergeAnalysislog_${ranks}_${gen}_${dim}.txt
#first argument is the index of the vessel to be blocked, if set to negative it means no vessels were damaged
srun -p medusa -n ${ranks} --mpi=pmi2 BloodFlowModeling -1 ${results_dir}/geometry_${ranks}_${gen}_${dim}.h5>>${results_dir}/BloodFlowModelinglog_${ranks}_${gen}_${dim}.txt


echo "Done!"
